version: '3'
services:
  db:
    container_name: movie-booking-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./volumes/postgres-prod:/var/lib/postgresql/data
    
  
  backend:
    container_name: movie-booking-backend
    image: denysbolshakov/movie-booking-backend
#    build: 
#      context: .
#      dockerfile: Dockerfile.backend
#      target: prod
    ports:
      - 5000:5000
    restart: always
    env_file:
      - .production.env
    volumes:
      - ./volumes/moviecovers-prod:/app/dist/static/moviecovers
    depends_on:
      - db

  migrations:
    container_name: movie-booking-migrations
    image: denysbolshakov/movie-booking-migrations
#    build:
#      context: .
#      dockerfile: Dockerfile.migrations
    env_file:
      - .production.env
    command: './database/scripts/wait-for-it.sh db:5432 -- ./database/scripts/migrate.sh'
    depends_on:
      - db

networks:
  default:
    ipam:
      config:
        - subnet: 172.37.0.0/16